name: vibeus
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  
  #For iOS
  cupertino_icons: ^1.0.0
  ## Firebase Storage
  firebase_storage: ^3.1.5
  
  #Firebase Core
  firebase_core: ^0.4.4+3
  
  # Firebase Auth
  firebase_auth: ^0.16.0
  
  # Cloud FireStore
  cloud_firestore: ^0.13.5
  
  #Flutter bloc method is used in Vbeus
  flutter_bloc: ^6.1.1
  
  #Meta package
  meta: ^1.1.8
  
  #Equatable packages
  equatable: ^1.1.1
  
  #rcdart package
  rxdart: ^0.23.0
  
  #File picker used to pick file type image in profile setup screen
  file_picker: ^1.9.0
  
  #Font awwesome flutter package
  font_awesome_flutter: ^8.8.1
  
  #eva icons flutter
  eva_icons_flutter: ^2.0.0
  
  #ectende image
  extended_image: ^1.5.0
  
  #time ago package
  timeago: 
  
  # UUID id used in image upload page to generate unique posId on our database
  uuid: ^2.0.4
  
  #image picker is used to pick images from gallery and camera
  image_picker: ^0.6.7+17
  
  #transparent image is used in discover screen
  transparent_image: ^1.0.0
  
  #flytter date time picker is used in profile setup screen
  flutter_datetime_picker: ^1.4.0
  
  #Material design icon
  material_design_icons_flutter:
  
  #Likify is used in bio and chats
  flutter_linkify: ^4.0.2
  
  #this also used in bio and chat
  url_launcher: ^5.7.10
  
  #onesignal is used for showing notifications
  onesignal_flutter: ^2.6.2
  
  #Not used yet
  advance_pdf_viewer: ^1.2.1+2
  
  #For geting location 
  geolocator: ^5.3.1
  
  #not yet used
  google_maps_flutter: ^1.1.1
  
  #Bottoom navgation bar
  google_nav_bar: ^3.0.0
  line_icons: ^0.2.0
  
  # Emojies
  emoji_picker: ^0.1.0
  carousel_slider: ^1.3.0



dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
      - images/profile.png
      - images/vibeuslogo.jpeg


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
